SEED: 20
MODEL:
  DEPTH: 18
  FREEZE_AT: 0  # All
  EMBED_DIM: 1024
  DROPOUT: 0.0
  NORMALIZE_EMBED: False
  FREEZE_BN: True
  LARGE_FC: False
  GLOBAL_POOL_TYPE: Max
SOLVER:
  OPTIM:
    NAME: SGD
    LR: 0.0001
    MOMENTUM: 0.9
    WDECAY: 0.001
  LOSS:
    NAME: triplet
    MARGIN: 1.0
    FOCAL_POW: 2.0
  MAX_ITERS: 100000
  VAL_STEP: True
  VAL_STEP_PERIOD: 5
  BATCH_SIZE: 8
  WORKERS: 4
  LOG_PERIOD: 50
  EVAL_PERIOD: 5000
  BAD_EVALS_TO_DECAY: 2
  BACKUP_PERIOD: 5000
DATA:
  BOX_SCALE: 1.0
  KEEP_RATIO: False
  RANDOM_BOX_OFFSET: null  # 0.5
  RANDOM_BOX_SCALE: null  # 1.5
  NORMALIZED_DEPTH: True
  AUGMENT_COLOR: False
INPUT:
  DEPTH: True
  NORMAL: False
  BG_INPUT: False
